/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tiendaDeVideo;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HernandezTique
 */
public class RentarJFrame extends javax.swing.JFrame {
    public Object o=new Object[7];
    private DefaultTableModel modelo;
    int contador=0;
    private String es="";
    private boolean ps=false;
    private boolean ss=false;
    /**
     * Creates new form RentarJFrame
     */
    public RentarJFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        cargarInterfazP();
        cargarDatosP();
        cargarInterfazS();
        cargarDatosS();
    }
    public static void buscarP(String buscarP){
        
    }
    public static void buscarS(String buscarS){
        
    }
    public void cargarInterfazP(){
        String datos[][]={};
        String columna[]={"Codigo", "Lanzamiento", "Nombre", "Categoria", "Formato", "Duracion", "Secuelas", "Estado"};
        modelo=new DefaultTableModel(datos,columna);
        jtPeliculas.setModel(modelo);
    }
    public void cargarDatosP(){
        Peliculas p;
        for (int i = 0; i < IngresarJFrame.Peliculas.size(); i++) {
            p=(Peliculas)IngresarJFrame.Peliculas.get(i);
            modelo.insertRow(contador,new Object[]{});
            modelo.setValueAt(p.codigo,contador,0);
            modelo.setValueAt(p.lanzamiento,contador,1);
            modelo.setValueAt(p.nombre,contador,2);
            modelo.setValueAt(p.categoria,contador,3);
            modelo.setValueAt(p.formato,contador,4);
            modelo.setValueAt(p.duracion,contador,5);
            modelo.setValueAt(p.secuelas,contador,6);
            modelo.setValueAt(p.estado,contador,7);
        }
    }
    public void cargarInterfazS(){
        String datos[][]={};
        String columna[]={"Codigo", "Lanzamiento", "Nombre", "Categoria", "Formato", "Duracion", "Temporadas", "Estado"};
        modelo=new DefaultTableModel(datos,columna);
        jtSeries.setModel(modelo);
    }
    public void cargarDatosS(){
        Series s; 
        for (int j=0;j<IngresarJFrame.Series.size();j++) {
            s=(Series)IngresarJFrame.Series.get(j);
            modelo.insertRow(contador,new Object[]{});
            modelo.setValueAt(s.codigo,contador,0);
            modelo.setValueAt(s.lanzamiento,contador,1);
            modelo.setValueAt(s.nombre,contador,2);
            modelo.setValueAt(s.categoria,contador,3);
            modelo.setValueAt(s.formato,contador,4);
            modelo.setValueAt(s.duracion,contador,5);
            modelo.setValueAt(s.temporadas,contador,6);
            modelo.setValueAt(s.estado,contador,7);
            //RentarJFrame.buscarS();
        }
        //modelo.addRow(o);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbltitulo = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        lblCodigo = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        lblMensaje = new javax.swing.JLabel();
        lblPeliculas = new javax.swing.JLabel();
        lblMensaje1 = new javax.swing.JLabel();
        lblSeries = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtPeliculas = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtSeries = new javax.swing.JTable();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbltitulo.setFont(new java.awt.Font("Myanmar Text", 1, 14)); // NOI18N
        lbltitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltitulo.setText("RENTAR");
        lbltitulo.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 153, 153), new java.awt.Color(0, 153, 153)));

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        lblCodigo.setText("Codigo:");

        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });

        lblMensaje.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblMensaje.setText("inserte el codigo de la pelicula que desea rentar");

        lblPeliculas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPeliculas.setText("Peliculas");
        lblPeliculas.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblMensaje1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMensaje1.setText("LISTA DE TODAS LAS PELICULAS Y SERIES");
        lblMensaje1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblSeries.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSeries.setText("Series");
        lblSeries.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jtPeliculas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Lanzamiento", "Nombre", "Categoria", "Formato", "Duracion", "Secuelas"
            }
        ));
        jtPeliculas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtPeliculasMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jtPeliculas);

        jtSeries.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Lanzamiento", "Nombre", "Categoria", "Formato", "Duracion", "Temporadas"
            }
        ));
        jtSeries.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtSeriesMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jtSeries);

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCodigo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblMensaje))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 828, Short.MAX_VALUE)
                        .addComponent(btnAceptar)
                        .addGap(18, 18, 18)
                        .addComponent(btnSalir)
                        .addContainerGap())
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lbltitulo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblMensaje1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane3)
                                .addComponent(lblPeliculas, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(48, 48, 48)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblSeries, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbltitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblMensaje1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSeries)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPeliculas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblMensaje)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCodigo)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnAceptar, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        String code=txtCodigo.getText();
        Peliculas p;
        Series s;
        if(es.equalsIgnoreCase("Rentado")){
            JOptionPane.showMessageDialog(null,"Rentado","MENSAJE",JOptionPane.WARNING_MESSAGE);
        }else{
            if(ps==true){
                for (int i=0;i<IngresarJFrame.Peliculas.size();i++) {
                    p=(Peliculas)IngresarJFrame.Peliculas.get(i);
                    if(p.codigo.equalsIgnoreCase(code)){
                        p.setEstado("Rentado");
                        JOptionPane.showMessageDialog(null,"Opcion realizada satisfactoriamente","MENSAJE",JOptionPane.INFORMATION_MESSAGE);
                    }
                }
            }else{
                for (int i=0;i<IngresarJFrame.Series.size();i++) {
                    s=(Series)IngresarJFrame.Series.get(i);
                   if(s.codigo.equalsIgnoreCase(code)){
                        s.setEstado("Rentado");
                        JOptionPane.showMessageDialog(null,"Opcion realizada satisfactoriamente","MENSAJE",JOptionPane.INFORMATION_MESSAGE);
                    }
                }
            }
        }
        //AQUÍ OCUPO QUE SE ACTUALICEN LAS TABLAS :U
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void jtPeliculasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtPeliculasMouseClicked
        int seleccionp = jtPeliculas.rowAtPoint(evt.getPoint());
        txtCodigo.setText(String.valueOf(jtPeliculas.getValueAt(seleccionp, 0)));
        es=String.valueOf(jtPeliculas.getValueAt(seleccionp, 7));
        ps=true;
        ss=false;
        //p=(Peliculas)IngresarJFrame.Peliculas.get(i);
        //txtCodigo.setText(modelo.getValueAt(s.generadorCodigo(),0).toString());
        //txtCodigo.setText(modelo.getValueAt(contador,1).toString());
        //txtCodigo.setText(modelo.getValueAt(contador,2).toString());
    }//GEN-LAST:event_jtPeliculasMouseClicked

    private void jtSeriesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtSeriesMouseClicked
        int seleccions = jtSeries.rowAtPoint(evt.getPoint());
        txtCodigo.setText(String.valueOf(jtSeries.getValueAt(seleccions, 0)));
        es=String.valueOf(jtSeries.getValueAt(seleccions, 7));
        ss=true;
        ps=false;
    }//GEN-LAST:event_jtSeriesMouseClicked

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RentarJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RentarJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RentarJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RentarJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RentarJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    public static javax.swing.JTable jtPeliculas;
    public static javax.swing.JTable jtSeries;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JLabel lblMensaje1;
    private javax.swing.JLabel lblPeliculas;
    private javax.swing.JLabel lblSeries;
    private javax.swing.JLabel lbltitulo;
    public static javax.swing.JTextField txtCodigo;
    // End of variables declaration//GEN-END:variables
}
